name: Build Bookmarklet

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Convert JS to Bookmarklet
      run: |
        cat script.js | sed 's|//.*$||g' | tr -d '\n' | sed 's/  */ /g' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^/javascript:(function(){/' | sed 's/$/})();/' > inline.js
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: inline.js
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
